kind: pipeline
name: default

steps:
- name: tag
  image: debian:10
  commands:
  - apt-get update
  - apt-get install -y jq curl
  - curl -s 'https://pypi.org/pypi/matrix-synapse/json' | jq -j -r '.info.version' > version
  - echo -n 'latest,' | cat - version > .tags
  - echo -n ',' | cat - version >> .tags
  - echo -n -$DRONE_BUILD_NUMBER >> .tags

# - name: docker-matrix-synapse
#   image: plugins/docker
#   settings:
#     repo: tlemarchand/matrix-synapse
#     target: app
#     username:
#       from_secret: docker_username
#     password:
#       from_secret: docker_password

- name: quay-matrix-synapse
  image: plugins/docker
  settings:
    repo: quay.io/tlemarchand/matrix-synapse
    target: app
    username:
      from_secret: quay_username
    password:
      from_secret: quay_password
    registry: quay.io